### ISSUE TITLE
Alchemical introduction Section 5.2  overlap 

### ISSUE THREAD

**Issue by jmichel80** [michellab/bssccpbiosim2022#12]
In [section 5.2](https://github.com/michellab/bssccpbiosim2022/blob/main/introduction_to_alchemistry/alchemical_introduction.ipynb)

![image](https://user-images.githubusercontent.com/11722212/189610964-92e1ccd5-f4bc-4a0a-af54-877173ce98dd.png)

The API for BSS.FreeEnergy.Relative.checkOverlap should be revisited. 
Returning a boolean is a confusing. False should mean that the overlap could not be checked, not that it has been checked and met a particular criteria. 
I would avoid writing that the OM is 'okay' the language lacks precision. We also do not know how reliable the 'rule of 0.03' is. 

For the tutorial it is better to simply plot the OM matrices and ask the delegates as an exercise to determine whether the runs pass the heuristic of the 'rule of 0.03'.

**Comment by annamherz** [comment]
The boolean return is based on this discussion - https://github.com/michellab/BioSimSpace/pull/365#discussion_r964666292 , so that it would be easier to incorporate in workflows, so that the user could then maybe submit the run with eg more windows. But it could be changed so it returns nothing and only throws a warning?

I'll change it so that for the workshop there is no check overlap used.
